version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finapi
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: finapi
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
